networks:
  traefik-public:
    external: true

services:
  web:
    image: laminebalde/portfolio:ubuntu-latest
    env_file:
      - .env
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.app-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.middlewares=https-redirect
      - traefik.http.routers.app-https.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=8080
    networks:
      - traefik-public
    volumes:
      - staticdata:/app/static

  traefik:
    image: traefik:v2.10
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.middlewares.https-compress.compress=true
      - traefik.http.middlewares.app-http.headers.stsSeconds=31536000
      - traefik.http.middlewares.app-http.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.app-http.headers.stsPreload=true
      - traefik.http.middlewares.app-http.headers.forceSTSHeader=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
      - /var/log/traefik:/var/log
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=mohamedlaminebalde392@gmail.com
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --log
      - --accesslog.filePath=/var/log/access.log
      - --api
    networks:
      - traefik-public

volumes:
  staticdata:
  traefik-public-certificates:
