# Generated by Django 5.1.1 on 2024-09-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
            ],
        ),
    ]
