# Generated by Django 5.1.1 on 2024-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_article_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('date_obtained', models.DateField()),
                ('badgeImage', models.ImageField(upload_to='certifications_badges/')),
            ],
        ),
    ]
