name: CI/CD portfolio

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
  build:
   name: Build & Push Docker Hub
   runs-on: ubuntu-latest
   needs: [check_syntaxe]

   steps:
     - uses: actions/checkout@v2

     - name: login to docker Hub
       env:
         DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
         DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
       run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

     - name: Build the Docker image
       run: docker build . -t laminebalde/portfolio:ubuntu-latest

     - name: Push the Docker image
       run: docker push laminebalde/portfolio:ubuntu-latest
